export const ANKLET_LIST_REQUEST = 'ANKLET_LIST_REQUEST';
export const ANKLET_LIST_SUCCESS = 'ANKLET_LIST_SUCCESS';
export const ANKLET_LIST_FAIL = 'ANKLET_LIST_FAIL';

export const ANKLET_DETAILS_REQUEST = 'ANKLET_DETAILS_REQUEST';
export const ANKLET_DETAILS_SUCCESS = 'ANKLET_DETAILS_SUCCESS';
export const ANKLET_DETAILS_FAIL = 'ANKLET_DETAILS_FAIL';