export const BRACELET_LIST_REQUEST = 'BRACELET_LIST_REQUEST';
export const BRACELET_LIST_SUCCESS = 'BRACELET_LIST_SUCCESS';
export const BRACELET_LIST_FAIL = 'BRACELET_LIST_FAIL';


export const BRACELET_DETAILS_REQUEST = 'BRACELET_DETAILS_REQUEST';
export const BRACELET_DETAILS_SUCCESS = 'BRACELET_DETAILS_SUCCESS';
export const BRACELET_DETAILS_FAIL = 'BRACELET_DETAILS_FAIL';