export const EARRING_LIST_REQUEST = 'EARRING_LIST_REQUEST';
export const EARRING_LIST_SUCCESS = 'EARRING_LIST_SUCCESS';
export const EARRING_LIST_FAIL = 'EARRING_LIST_FAIL';


export const EARRING_DETAILS_REQUEST = 'EARRING_DETAILS_REQUEST';
export const EARRING_DETAILS_SUCCESS = 'EARRING_DETAILS_SUCCESS';
export const EARRING_DETAILS_FAIL = 'EARRING_DETAILS_FAIL';