export const NECKLACE_LIST_REQUEST = 'NECKLACE_LIST_REQUEST';
export const NECKLACE_LIST_SUCCESS = 'NECKLACE_LIST_SUCCESS';
export const NECKLACE_LIST_FAIL = 'NECKLACE_LIST_FAIL';

export const NECKLACE_DETAILS_REQUEST = 'NECKLACE_DETAILS_REQUEST';
export const NECKLACE_DETAILS_SUCCESS = 'NECKLACE_DETAILS_SUCCESS';
export const   NECKLACE_DETAILS_FAIL = 'NECKLACE_DETAILS_FAIL';