const data = {
    earrings: [
      {
        _id: '1',
        name: 'Kash Earring',
        category: 'Earrings',
        image: '/earringimages/Earring1.jpeg',
        price: 140,
        countInStock: 10,
        brand: 'Kash',
        rating: 4,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: 'Ash Earring',
        category: 'Earrings',
        image: '/earringimages/Earring2.jpeg',
        price: 120,
        countInStock: 20,
        brand: 'Ash',
        rating: 5,
        numReviews: 8,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'Harry Earring',
        category: 'Earrings',
        image: '/earringimages/Earring3.jpeg',
        price: 150,
        countInStock: 0,
        brand: 'Harry',
        rating: 4.5,
        numReviews: 9,
        description: 'high quality product',
      },
      {
        _id: '4',
        name: 'Kash moon',
        category: 'Earrings',
        image: '/earringimages/Earring5.jpeg',
        price: 170,
        brand: 'Kash',
        rating: 5,
        numReviews: 7,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'Kanishq Earring',
        category: 'Earrings',
        image: '/earringimages/Earring6.jpeg',
        price: 120,
        countInStock: 15,
        brand: 'Kanishq',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '6',
        name: 'Tanishq Earring',
        category: 'Earrings',
        image: '/earringimages/Earring9.jpeg',
        price: 190,
        countInStock: 5,
        brand: 'TanishqEarring',
        rating: 5,
        numReviews: 8,
        description: 'high quality product',
      },
      {
        _id: '7',
        name: 'Cider',
        category: 'Earrings',
        image: '/earringimages/Earring11.jpeg',
        price: 160,
        countInStock: 5,
        brand: 'Mosh',
        rating: 4,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '8',
        name: 'Mosh Earring',
        category: 'Earrings',
        image: '/earringimages/Earring12.jpeg',
        price: 120,
        countInStock: 12,
        brand: 'Mosh',
        rating: 3.5,
        numReviews: 9,
        description: 'high quality product',
      },
    ],





    necklaces: [
      {
        _id: '1',
        name: 'Kash necklace',
        category: 'necklaces',
        image: '/necklaceimages/necklace1.jpeg',
        price: 140,
        countInStock: 10,
        brand: 'Kash',
        rating: 4,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: 'Ash necklace',
        category: 'necklaces',
        image: '/necklaceimages/necklace2.jpeg',
        price: 120,
        countInStock: 20,
        brand: 'Ash',
        rating: 5,
        numReviews: 8,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'Harry necklace',
        category: 'necklaces',
        image: '/necklaceimages/necklace3.jpeg',
        price: 150,
        countInStock: 0,
        brand: 'Harry',
        rating: 4.5,
        numReviews: 9,
        description: 'high quality product',
      },
      {
        _id: '4',
        name: 'Kash moon',
        category: 'necklaces',
        image: '/necklaceimages/necklace4.jpeg',
        price: 170,
        brand: 'Kash',
        rating: 5,
        numReviews: 7,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'Kanishq necklace',
        category: 'necklaces',
        image: '/necklaceimages/necklace5.jpeg',
        price: 120,
        countInStock: 15,
        brand: 'Kanishq',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '6',
        name: 'Tanishq necklace',
        category: 'necklaces',
        image: '/necklaceimages/necklace6.jpeg',
        price: 190,
        countInStock: 5,
        brand: 'Tanishqnecklace',
        rating: 5,
        numReviews: 8,
        description: 'high quality product',
      },
      {
        _id: '7',
        name: 'Cider',
        category: 'necklaces',
        image: '/necklaceimages/necklace7.jpeg',
        price: 160,
        countInStock: 5,
        brand: 'Mosh',
        rating: 4,
        numReviews: 10,
        description: 'high quality product',
      },
     
    ],




    bracelets: [
      {
        _id: '1',
        name: 'Kash bracelet',
        category: 'bracelets',
        image: '/braceletimages/bracelet1.jpeg',
        price: 140,
        countInStock: 10,
        brand: 'Kash',
        rating: 4,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: 'Ash bracelet',
        category: 'bracelets',
        image: '/braceletimages/bracelet2.jpeg',
        price: 120,
        countInStock: 20,
        brand: 'Ash',
        rating: 5,
        numReviews: 8,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'Harry bracelet',
        category: 'bracelets',
        image: '/braceletimages/bracelet3.jpeg',
        price: 150,
        countInStock: 0,
        brand: 'Harry',
        rating: 4.5,
        numReviews: 9,
        description: 'high quality product',
      },
      {
        _id: '4',
        name: 'Kash moon',
        category: 'bracelets',
        image: '/braceletimages/bracelet4.jpeg',
        price: 170,
        brand: 'Kash',
        rating: 5,
        numReviews: 7,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'Kanishq bracelet',
        category: 'bracelets',
        image: '/braceletimages/bracelet5.jpeg',
        price: 120,
        countInStock: 15,
        brand: 'Kanishq',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '6',
        name: 'Tanishq bracelet',
        category: 'bracelets',
        image: '/braceletimages/bracelet6.jpeg',
        price: 190,
        countInStock: 5,
        brand: 'Tanishqbracelet',
        rating: 5,
        numReviews: 8,
        description: 'high quality product',
      },
      {
        _id: '7',
        name: 'Cider',
        category: 'bracelets',
        image: '/braceletimages/bracelet7.jpeg',
        price: 160,
        countInStock: 5,
        brand: 'Mosh',
        rating: 4,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '8',
        name: 'Mosh bracelet',
        category: 'bracelets',
        image: '/braceletimages/bracelet8.jpeg',
        price: 120,
        countInStock: 12,
        brand: 'Mosh',
        rating: 3.5,
        numReviews: 9,
        description: 'high quality product',
      },
    ],



    anklets: [
      {
        _id: '1',
        name: 'Kash anklet',
        category: 'anklets',
        image: '/ankletimages/anklet1.jpeg',
        price: 140,
        countInStock: 10,
        brand: 'Kash',
        rating: 4,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: 'Ash anklet',
        category: 'anklets',
        image: '/ankletimages/anklet2.jpeg',
        price: 120,
        countInStock: 20,
        brand: 'Ash',
        rating: 5,
        numReviews: 8,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'Harry anklet',
        category: 'anklets',
        image: '/ankletimages/anklet3.jpeg',
        price: 150,
        countInStock: 0,
        brand: 'Harry',
        rating: 4.5,
        numReviews: 9,
        description: 'high quality product',
      },
      {
        _id: '4',
        name: 'Kash moon',
        category: 'anklets',
        image: '/ankletimages/anklet4.jpeg',
        price: 170,
        brand: 'Kash',
        rating: 5,
        numReviews: 7,
        description: 'high quality product',
      },
      
    ],




    
  };
  export default data;
  