const data = {
    earrings: [
      {
        _id: '1',
        name: 'Kash Earring',
        category: 'Earrings',
        image: '/earringimages/Earring1.jpeg',
        price: 120,
        brand: 'Kash',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: 'Ash Earring',
        category: 'Earrings',
        image: '/earringimages/Earring2.jpeg',
        price: 120,
        brand: 'Ash',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'Harry Earring',
        category: 'Earrings',
        image: '/earringimages/Earring3.jpeg',
        price: 120,
        brand: 'Harry',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '4',
        name: 'Kash moon',
        category: 'Earrings',
        image: '/earringimages/Earring5.jpeg',
        price: 120,
        brand: 'Kash',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'Kanishq Earring',
        category: 'Earrings',
        image: '/earringimages/Earring6.jpeg',
        price: 120,
        brand: 'Kanishq',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '6',
        name: 'Tanishq Earring',
        category: 'Earrings',
        image: '/earringimages/Earring9.jpeg',
        price: 120,
        brand: 'TanishqEarring',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '7',
        name: 'Cider',
        category: 'Earrings',
        image: '/earringimages/Earring11.jpeg',
        price: 120,
        brand: 'Mosh',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '8',
        name: 'Mosh Earring',
        category: 'Earrings',
        image: '/earringimages/Earring12.jpeg',
        price: 120,
        brand: 'Mosh',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
    ],
  };
  export default data;
  